server:
  port: 9000
spring:
  liquibase:
    enabled: true
    change-log: db/changelog/changelog-master.xml
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5436/hamed
    username: hamed
    password: hamed
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    port: '587'